### PR TITLE
Extra gridstack item attributes

### PR DESCRIPTION
**Pull request by Kobe-Wulteputte**
Added bindable gs item attributes:
* minW
* maxW
* minH
* maxH
* id

Also updated readme with example

### CODE REVIEW

**Comment by MaximBalaganskiy** [comment]
Could you please double the changes in au2 branch as well?

**Comment by MaximBalaganskiy** [comment]
Is this still relevant?

**Comment by alexandr-todorov** [comment]
Hello Maxim,
yes, the absence of the above properties does not allow us to fully use all the functions of the gridstack.
I just duplicated them in the au2 branch.
Are there any difficulties with the approval of this PR?

Best regards,
Alexandr

**Comment by MaximBalaganskiy** [comment]
@alexandr-todorov I'm not quite sure overriding Id attribute is going to work. Have you tested it in both branches?

**Comment by alexandr-todorov** [comment]
> @alexandr-todorov I'm not quite sure overriding Id attribute is going to work. Have you tested it in both branches?

I just pushed some additional changes, take a look please.
id attribute was tested only in au2 branch.

**Pull request merged**
